/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        System.out.println("Running Train-Booking System");

        Scanner scanner = new Scanner(System.in);

    }
}
